### ISSUE TITLE
Apple Silicon Could not initialize class org.zeroturnaround.process.unix.LibC.

### ISSUE THREAD

**Issue by jongyu** [zeroturnaround/zt-exec#102]
```java
at org.zeroturnaround.process.UnixProcess.kill(UnixProcess.java:46)
at org.zeroturnaround.process.UnixProcess.destroy(UnixProcess.java:34)
at org.zeroturnaround.process.AbstractProcess.destroyForcefully(AbstractProcess.java:113)
```

**Comment by toomasr** [comment]
How to reproduce this?

**Comment by neeme-praks-sympower** [comment]
BTW, you seem to have filed this issue under the wrong project. Judging by the class names, this issue belongs to https://github.com/zeroturnaround/zt-process-killer

I ran `zt-process-killer` unit tests on my MacBook Pro M1 and they all passed without issues. Please specify the steps to take (and in which environment) in order to reproduce this.

**Comment by nemecec** [comment]
BTW, you seem to have filed this issue under the wrong project. Judging by the class names, this issue belongs to https://github.com/zeroturnaround/zt-process-killer

I ran `zt-process-killer` unit tests on my MacBook Pro M1 and they all passed without issues. Please specify the steps to take (and in which environment) in order to reproduce this.
