### ISSUE TITLE
Support for Process.destroyForcibly() and .isAlive() from Java 8

### ISSUE THREAD

**Issue by Happy-Neko** [zeroturnaround/zt-exec#19]
Java 8 added two nice methods to `Process` class. http://docs.oracle.com/javase/8/docs/api/java/lang/Process.html

**Comment by kincajou** [comment]
Hello. 

I'm using my custom implementation of ProcessStopper but since it is executed in thread separate from the one where ProcessExecutor is created, there is no context.
I.e. stopper destroys the process and it leaves some temp files behind. It would be good to know which process it is so i can clean up manually.

There is a way to do it via custom ExecuteStreamHandler' stop() method which is executed after stopper.stop(), but it seems wrong.

What would be good is to have a copy of executor.environment(Map) in ProcessStopper, that way i can pass some info down there.

**Comment by reinra** [comment]
Hey,

Unfortunately I can't change ProcessStopper interface easily without
breaking the backward compatibility.
you could use a static map to match process instances with the temp folders.
ProcessListener.afterStart() can help you to match Process with the
ProcessExecutor instance (you can register listener by
ProcessExecutor.addListener()).
Would that help?

On Wed, Mar 18, 2015 at 12:23 PM, Nick Voznesenskiy <
notifications@github.com> wrote:

> Hello.
>
> I'm using my custom implementation of ProcessStopper but since it is
> executed in thread separate from the one where ProcessExecutor is created,
> there is no context.
> I.e. stopper destroys the process and it leaves some temp files behind. It
> would be good to know which process it is so i can clean up manually.
>
> There is a way to do it via custom ExecuteStreamHandler' stop() method
> which is executed after stopper.stop(), but it seems wrong.
>
> What would be good is to have a copy of executor.environment(Map) in
> ProcessStopper, that way i can pass some info down there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zeroturnaround/zt-exec/issues/19#issuecomment-82880588>
> .
>



-- 
Rein Raudjärv
ZeroTurnaround

**Comment by kincajou** [comment]
Sorry, i completely overlooked that i can pass anything i want to the custom implementation of the stopper itself. So all is well, sorry for false alarm. :-)

**Comment by reinra** [comment]
Ok.

On Fri, Mar 20, 2015 at 10:50 AM, Nick Voznesenskiy <
notifications@github.com> wrote:

> Sorry, i completely overlooked that i can pass anything i want to the
> custom implementation of the stopper itself. So all is well, sorry for
> false alarm. :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zeroturnaround/zt-exec/issues/19#issuecomment-83958343>
> .
>



-- 
Rein Raudjärv
ZeroTurnaround
