### ISSUE TITLE
Add WindowsProcess.isAlive() implmentation using tasklist instead of wmic

### ISSUE THREAD

**Issue by reinra** [zeroturnaround/zt-exec#28]
Sometimes the wmic.exe may be missing from the system.

**Comment by iirekm** [comment]
I'm not sure if even `tasklist.exe` is present on all editions of Windows. It's hard to find exact information about that, but from my experience, even basic commands may be missing in older or Home / Basic editions of Windows.

I think the better way is to use Windows API, through JNA library for example. MSDN docs say exactly since which Windows version which function is available, and there's no need to sprawn a separate process just to check status of some other process.

**Comment by reinra** [comment]
Moved the issue under correct project.
